### ISSUE TITLE
Adding user modules to PPI-ext

### ISSUE THREAD

**Issue by ketilt** [KSSno/Klimakverna-Pilot1#19]
We should figure out and document how we can do this, or try to request the possibility.

Currently, we have to source an old conda version which has a poor solver. It's also inconvenient if we have to wait on tickets to install further software that we need. Can we instead make our own modules, so we can have the conda version we want as well as any other packages that we require in Klimakverna?

### Subtasks
- [ ] Look through existing PPI documentation on modules and see if this works in PPI-ext
- [ ] Look through previous communications with IT infra on this topic
- [ ] Get conda version 24 instead of version 4 available on PPI-ext
- [ ] Add other user-modules we might need, if possible
